[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pftp"
version = "2.0.5"
description = "PFTP - Pentest File Transfer Protocols - CLI Tool"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [{name = "Ahmad Alawneh", email = "a.3alawneh@gmail.com"}]
keywords = ["pentest", "file-transfer", "security", "hacking", "ctf", "ftp", "CTF", "offensive security", "red team", "blue team", "cybersecurity", "pentesting", "ethical hacking", "HTB", "THM", "penetration testing"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Security",
]

dependencies = [
    "click>=8.0",
    "docker>=6.0",
    "pyyaml>=6.0",
    "rich>=13.0",
]

[project.scripts]
pftp = "pftp.cli:cli"

[project.optional-dependencies]
dev = ["build", "twine"]


[tool.setuptools.packages.find]
where = ["."]
